{{- if .Values.cleaner.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "service-gateway.fullname" . }}-gwclass-cleaner
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: {{ include "service-gateway.fullname" . }}-gwclass-cleaner
      automountServiceAccountToken: true
      containers:
        - name: kubectl
          {{- if eq "true" ( include "distro.openshift" . ) }}
          securityContext:
            {{- toYaml (omit .Values.cleaner.securityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 12 }}
          {{- else }}
          securityContext:
            {{- toYaml .Values.cleaner.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.cleaner.registry }}/{{ .Values.cleaner.repository }}:{{ .Values.cleaner.tag }}"
          imagePullPolicy: {{ .Values.cleaner.pullPolicy }}
          command:
          - /bin/sh
          - -c
          - |
            kubectl patch gatewayclass {{ include "tenant.name" . }} --type=merge -p '{"metadata":{"finalizers":null}}' || true
      restartPolicy: Never
{{- end }}
