{{- if and .Values.cleaner.enabled .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-gateway.fullname" . }}-gwclass-cleaner
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}
