{{- if .Values.cleaner.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-gateway.fullname" . }}-gwclass-cleaner
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}
