{{ $defaults := dict "registryFQDN" (include "registry.ghcr" $) }}

{{ $vals := dig "gcp-credential-manager" "values" (dict) .Values.helm.releases }}
{{ $vals = mergeOverwrite $defaults $vals }}

{{- if eq (include "distro.openshift" $) "true" }}
{{ $vals = mergeOverwrite $vals (dict "distro" .Values.distro) }}
{{- end }}

apiVersion: ui.k8s.appscode.com/v1alpha1
kind: Feature
metadata:
  name: gcp-credential-manager
  labels:
    app.kubernetes.io/part-of: capi-capg
spec:
  title: GCP Credential Manager
  description: |
    GCP Credential Manager
  icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/cluster.svg
      type: image/svg+xml
  featureSet: capi-capg
  featureBlock: gcp-credential-manager
  recommended: true
  readinessChecks:
    workloads:
      - group: apps
        version: v1
        kind: Deployment
        selector:
          app.kubernetes.io/name: gcp-credential-manager
  chart:
    name: gcp-credential-manager
    namespace: capg-system
    createNamespace: {{ $.Values.helm.createNamespace }}
    version: {{ dig "gcp-credential-manager" "version" "" $.Values.helm.releases }}
    sourceRef:
      kind: HelmRepository
      name: appscode-charts-oci
      namespace: {{ .Release.Namespace }}
{{- with $vals }}
  {{- dict "values" . | toYaml | nindent 2 }}
{{- end }}
