apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    chart: cluster-autoscaler
    repoURL: ghcr.io/appscode-charts
    targetRevision: 9.29.0
    helm:
      values: |
        ace-user-roles:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: capi-system
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
