apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aceshifter
  namespace: argocd
spec:
  project: default
  source:
    chart: aceshifter
    repoURL: ghcr.io/appscode-charts
    targetRevision: v2026.3.30
    helm:
      values: |
        ace-user-roles:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeops
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
