apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-shard-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: operator-shard-manager
    repoURL: ghcr.io/appscode-charts
    targetRevision: v2026.1.15
    helm:
      values: |
        ace-user-roles:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeops
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

  ignoreDifferences:
  - jsonPointers:
    - /data
    kind: Secret
    name: operator-shard-manager-apiserver-cert
    namespace: kubeops
  - group: apiregistration.k8s.io
    kind: APIService
    name: v1alpha1.ui.openviz.dev
    jsonPointers:
    - /spec/caBundle
  - group: apps
    kind: Deployment
    name: operator-shard-manager
    namespace: kubeops
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1apiregistration.yaml
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
    jsonPointers:
    - /metadata/annotations
    - /spec
