project:
  name: S3Proxy
  shortName: S3Proxy
  url: https://github.com/appscode-cloud
  description: S3Proxy Deployment
  app: a S3Proxy
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: s3proxy
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.29+
release:
  name: s3proxy
  namespace: ace
