{{- if eq (toString .Values.global.platform.deploymentType) "Hosted" }}
apiVersion: v1
kind: Service
metadata:
  name: selfhost
  namespace: {{ .Release.Namespace }}
spec:
  externalName: {{ if .Values.gateway.enabled }}{{ .Values.gateway.rules.selfhost.upstream }}{{ else }}{{ .Values.ingress.rules.selfhost.upstream }}{{ end }}
  sessionAffinity: None
  type: ExternalName
{{- end }}
