apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-manager-spoke
  namespace: argocd
spec:
  project: default
  source:
    chart: cluster-manager-spoke
    repoURL: ghcr.io/appscode-charts
    targetRevision: v2026.2.16
    helm:
      values: |
        ace-user-roles:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: open-cluster-management
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
