{{ if and (index .Values "gateway" "enabled") (index .Values "ingress-nginx" "enabled") }}

{{- $secretName := printf "%s-cert" (include "ace.fullname" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ace.fullname" . }}-ingress-cert
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ index $existing.data "tls.crt" }}
  tls.key: {{ index $existing.data "tls.key" }}
{{- end }}

{{- end }}
