{{- if (index .Values "gateway" "enabled") }}
{{- $oldName := printf "%s-cert" (include "ace.fullname" .) }}
{{- $oldSecret := lookup "v1" "Secret" .Release.Namespace $oldName }}
{{- if $oldSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ace.fullname" . }}-ingress-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: {{ $oldSecret.type }}
data:
{{- range $k, $v := $oldSecret.data }}
  {{ $k }}: {{ $v }}
{{- end }}
{{- end }}
{{- end }}
