apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtual-secrets-server
  namespace: argocd
spec:
  project: default
  source:
    chart: virtual-secrets-server
    repoURL: ghcr.io/appscode-charts
    targetRevision: v2026.2.27
    helm:
      values: |
        ace-user-roles:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubevault
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

  ignoreDifferences:
  - jsonPointers:
    - /data
    kind: Secret
    name: virtual-secrets-server-apiserver-cert
    namespace: kubevault
  - group: apiregistration.k8s.io
    kind: APIService
    name: v1alpha1.ui.openviz.dev
    jsonPointers:
    - /spec/caBundle
  - group: apps
    kind: Deployment
    name: virtual-secrets-server
    namespace: kubevault
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1apiregistration.yaml
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
    jsonPointers:
    - /metadata/annotations
    - /spec
