apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ace-installer.fullname" . }}-check
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 4
  manualSelector: true
  selector:
    matchLabels:
      {{- include "ace-installer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ace-installer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ace-installer.fullname" . }}-check
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.helm.releases.ace.version }}"
          imagePullPolicy: Always
          args:
            - check
            - --check-config=/data/b3/conf/config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: data
              mountPath: /data
            - name: check-config
              mountPath: /data/b3/conf/config.yaml
              subPath: config.yaml
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: check-config
          secret:
            defaultMode: 420
            secretName: {{ include "ace-installer.fullname" . }}-check-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
