{{- $ns := "monitoring" -}}
{{- if eq (include "distro.openshift" .) "true" -}}
{{- $ns = "openshift-user-workload-monitoring" -}}
{{- else if eq (include "distro.rancher" .) "true" -}}
{{- $ns = "cattle-monitoring-system" -}}
{{- end -}}

{{- if and (ne $ns "openshift-user-workload-monitoring") (ne $ns "cattle-monitoring-system") }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
---
{{- end }}

{{- if and .Values.alertmanager.email.enabled .Values.alertmanager.email.authSecretName .Values.alertmanager.email.authSecretKey .Values.alertmanager.email.authPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.alertmanager.email.authSecretName }}
  namespace: {{ $ns }}
stringData:
  {{ .Values.alertmanager.email.authSecretKey }}: {{ .Values.alertmanager.email.authPassword | quote }}
---
{{- end }}

{{- if and .Values.alertmanager.webhook.enabled .Values.alertmanager.webhook.urlSecretName .Values.alertmanager.webhook.urlSecretKey .Values.alertmanager.webhook.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.alertmanager.webhook.urlSecretName }}
  namespace: {{ $ns }}
stringData:
  {{ .Values.alertmanager.webhook.urlSecretKey }}: {{ .Values.alertmanager.webhook.url | quote }}
{{- end }}
