{{- $ns := "monitoring" -}}
{{- if eq (include "distro.openshift" .) "true" -}}
{{- $ns = "openshift-user-workload-monitoring" -}}
{{- else if eq (include "distro.rancher" .) "true" -}}
{{- $ns = "cattle-monitoring-system" -}}
{{- end -}}

{{- if and (ne $ns "openshift-user-workload-monitoring") (ne $ns "cattle-monitoring-system") }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
---
{{- end }}

{{- $alertmanager := dig "monitoring-operator" "values" "alertmanager" (dict) .Values.helm.releases -}}

{{- if and (dig "email" "enabled" false $alertmanager) (dig "email" "secret" "name" "" $alertmanager) (dig "email" "secret" "key" "" $alertmanager) (dig "email" "secret" "password" "" $alertmanager) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ dig "email" "secret" "name" "" $alertmanager }}
  namespace: {{ $ns }}
stringData:
  {{ dig "email" "secret" "key" "" $alertmanager }}: {{ dig "email" "secret" "password" "" $alertmanager | quote }}
---
{{- end }}

{{- if and (dig "webhook" "enabled" false $alertmanager) (dig "webhook" "secret" "name" "" $alertmanager) (dig "webhook" "secret" "key" "" $alertmanager) (dig "webhook" "secret" "url" "" $alertmanager) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ dig "webhook" "secret" "name" "" $alertmanager }}
  namespace: {{ $ns }}
stringData:
  {{ dig "webhook" "secret" "key" "" $alertmanager }}: {{ dig "webhook" "secret" "url" "" $alertmanager | quote }}
{{- end }}
