{{- $ns := "monitoring" -}}
{{- if eq (include "distro.openshift" .) "true" -}}
{{- $ns = "openshift-user-workload-monitoring" -}}
{{- else if eq (include "distro.rancher" .) "true" -}}
{{- $ns = "cattle-monitoring-system" -}}
{{- end -}}

{{- if and .Values.notifications.email.enabled .Values.notifications.email.authPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-email-auth
  namespace: {{ $ns }}
stringData:
  password: {{ .Values.notifications.email.authPassword | quote }}
---
{{- end }}

{{- if and .Values.notifications.webhook.enabled .Values.notifications.webhook.url }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-webhook-url
  namespace: {{ $ns }}
stringData:
  url: {{ .Values.notifications.webhook.url | quote }}
---
{{- end }}

{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1alpha1/AlertmanagerConfig") .Values.notifications.email.enabled .Values.notifications.email.to .Values.notifications.email.from .Values.notifications.email.smarthost }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: installer-email
  namespace: {{ $ns }}
  labels:
    {{ .Values.alertmanagerConfigSelector.labelKey }}: {{ .Values.alertmanagerConfigSelector.labelValue | quote }}
spec:
  receivers:
  - name: installer-email
    emailConfigs:
    - to: {{ .Values.notifications.email.to | quote }}
      from: {{ .Values.notifications.email.from | quote }}
      smarthost: {{ .Values.notifications.email.smarthost | quote }}
      authUsername: {{ .Values.notifications.email.authUsername | quote }}
      {{- if .Values.notifications.email.authPassword }}
      authPassword:
        name: alertmanager-email-auth
        key: password
      {{- end }}
      requireTLS: {{ .Values.notifications.email.requireTLS }}
      sendResolved: {{ .Values.notifications.email.sendResolved }}
  route:
    groupBy:
    - job
    groupWait: 10s
    groupInterval: 1m
    receiver: installer-email
    repeatInterval: 1h
    continue: {{ .Values.notifications.email.continue }}
    matchers: []
---
{{- end }}

{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1alpha1/AlertmanagerConfig") .Values.notifications.webhook.enabled .Values.notifications.webhook.url }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: installer-webhook
  namespace: {{ $ns }}
  labels:
    {{ .Values.alertmanagerConfigSelector.labelKey }}: {{ .Values.alertmanagerConfigSelector.labelValue | quote }}
spec:
  receivers:
  - name: installer-webhook
    webhookConfigs:
    - urlSecret:
        name: alertmanager-webhook-url
        key: url
      sendResolved: {{ .Values.notifications.webhook.sendResolved }}
      maxAlerts: 0
  route:
    groupBy:
    - job
    groupWait: 10s
    groupInterval: 1m
    receiver: installer-webhook
    repeatInterval: 1h
    continue: {{ .Values.notifications.webhook.continue }}
    matchers: []
{{- end }}
