{{- if .Values.vaultServer.serverAddress }}
# TCP passthrough: vault terminates TLS itself, so spokes see the cert signed by the
# vault CA that the hub AppBinding hands them as caBundle.
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: ace
  listeners:
    - name: vault-tcp
      protocol: TCP
      port: 8200
    - name: grpc-proxy-tcp
      protocol: TCP
      port: 50053
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: vault
      sectionName: vault-tcp
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.vaultServer.name }}
          port: 8200
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: vault-grpc-proxy
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: vault
      sectionName: grpc-proxy-tcp
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.vaultServer.name }}
          port: 50053
          weight: 1
{{- end }}
