# backups
# tls encrypt
# monitoring

apiVersion: kubevault.com/v1alpha2
kind: VaultServer
metadata:
  name: {{ .Values.vaultServer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-vault.labels" . | nindent 4 }}
spec:
  allowedSecretEngines:
    namespaces:
      from: All
  isolateTenants: {{ .Values.vaultServer.isolateTenants }}
  version: {{ .Values.vaultServer.version | quote }}
  replicas: {{ .Values.vaultServer.replicas }}
  tls:
    issuerRef:
      name: {{ include "service-vault.fullname" . }}-ca-issuer
      kind: Issuer
      apiGroup: cert-manager.io
  backend:
    raft:
      storage:
        {{- with .Values.vaultServer.persistence.storageClassName }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.vaultServer.persistence.size }}
  unsealer:
    secretShares: {{ .Values.vaultServer.unsealer.secretShares }}
    secretThreshold: {{ .Values.vaultServer.unsealer.secretThreshold }}
    mode:
      kubernetesSecret:
        secretName: {{ .Values.vaultServer.name }}-keys
  {{- if ne (toString .Values.vaultServer.serviceType) "ClusterIP" }}
  serviceTemplates:
    - alias: vault
      spec:
        type: {{ .Values.vaultServer.serviceType }}
  {{- end }}
  relayPlacementRef:
    name: {{ include "service-vault.fullname" . }}-relay
  relayTemplate:
    namespace: {{ .Values.vaultServer.relay.namespace }}
    bootstrapTokenTTL: {{ .Values.vaultServer.relay.bootstrapTokenTTL }}
  monitor:
    agent: prometheus.io
    prometheus:
      exporter:
        resources: {}
  terminationPolicy: {{ .Values.vaultServer.terminationPolicy }}
