{{ $objstore := .Values.global.infra.objstore }}

{{- if and (include "settings.objstoreSecretName" .) (or $objstore.s3 $objstore.azure $objstore.gcs) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "settings.objstoreSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with $objstore.s3 }}
  AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  ca.crt: {{ .CA_CERT_DATA | default "" | quote }}
  {{- with .AWS_REGION }}
  AWS_REGION: '{{ . }}'
  {{- end }}
{{- end }}

{{- with $objstore.azure }}
  AZURE_ACCOUNT_NAME: '{{ .AZURE_ACCOUNT_NAME }}'
  AZURE_ACCOUNT_KEY: '{{ .AZURE_ACCOUNT_KEY }}'
{{- end }}

{{- with $objstore.gcs }}
  sa.json: {{ .GOOGLE_SERVICE_ACCOUNT_JSON_KEY | default "" | quote }}
{{- end }}

{{- end }}
