{{- $secretName := include "settings.platformUserConfigSecretName" . -}}
{{- $secretNS   := .Release.Namespace -}}
{{- if not (lookup "v1" "Secret" $secretNS $secretName) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "settings.platformUserConfigSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
stringData:
  user.ini: |-
    [service]
    EMAIL_DOMAIN_WHITELIST = {{ join "," .Values.settings.platform.serviceDomainWhiteList }}
{{- if kindIs "bool" .Values.settings.platform.disableRegularOrgCreation }}

    [admin]
    DISABLE_REGULAR_ORG_CREATION = {{ .Values.settings.platform.disableRegularOrgCreation }}
{{- end }}

    [branding]
    APP_NAME = {{ .Values.settings.platform.appName }}
    LOGO = `{{ .Values.branding.logo }}`
    FAVICON = `{{ .Values.branding.favicon }}`
    PRIMARY_COLOR = `{{ .Values.branding.primaryColor }}`
    SHOW_APP_TAG = {{ .Values.branding.showAppTag }}
{{- end }}
