apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: monitoring-operator
    repoURL: ghcr.io/appscode-charts
    targetRevision: v2026.3.30
    helm:
      values: |
        tolerations:
          - key: "role"
            operator: "Equal"
            value: "worker_node_svc"
            effect: "NoSchedule"
        monitoring:
          agent: "prometheus.io/operator"
          serviceMonitor:
            labels:
              release: prometheus-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

  ignoreDifferences:
  - jsonPointers:
    - /data
    kind: Secret
    name: monitoring-operator-apiserver-cert
    namespace: monitoring
  - group: apiregistration.k8s.io
    kind: APIService
    name: v1alpha1.ui.openviz.dev
    jsonPointers:
    - /spec/caBundle
  - group: apps
    kind: Deployment
    name: monitoring-operator
    namespace: monitoring
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1apiregistration.yaml
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
    jsonPointers:
    - /metadata/annotations
    - /spec
