apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    chart: kyverno
    repoURL: ghcr.io/appscode-charts
    targetRevision: 3.2.6
    helm:
      values: |
        ace-user-roles:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
