{{- if and (eq (toString .Values.global.platform.deploymentType) "Hosted") (index .Values "ingress" "enabled") }}
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: {{ .Release.Namespace }}
spec:
  externalName: {{ .Values.ingress.rules.blog.upstream }}
  sessionAffinity: None
  type: ExternalName
{{- end }}
