apiVersion: v2
name: rustfs
description: A Helm chart for RustFS Demo Deployment
type: application
version: v2026.9.11
appVersion: 1.0.0
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/bytebuilders/icons/android-icon-192x192.png
sources:
- https://github.com/appscode-cloud
maintainers:
- name: appscode
  email: support@appscode.com
