project:
  name: RustFS
  shortName: RustFS
  url: https://github.com/appscode-cloud
  description: RustFS Demo Deployment
  app: a RustFS
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: rustfs
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.29+
release:
  name: rustfs
  namespace: ace
