apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb-provider-gcp
  namespace: argocd
spec:
  project: default
  source:
    chart: kubedb-provider-gcp
    repoURL: ghcr.io/appscode-charts
    targetRevision: v2024.1.31
    helm:
      values: |
        ace-user-roles:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
