{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- $criticalAddon := and .Values.criticalAddon (or (eq .Release.Namespace "kube-system") (and (ge $major 1) (ge $minor 17))) -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rustfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "rustfs.fullname" . }}-pods
  selector:
    matchLabels:
      {{- include "rustfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rustfs.selectorLabels" . | nindent 8 }}
      {{- if $criticalAddon }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "appscode.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: rustfs
        {{- if eq "true" ( include "distro.openshift" . ) }}
        securityContext:
          {{- toYaml (omit .Values.securityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 10 }}
        {{- else }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        image: "{{ include "rustfs.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "mkdir -p /data/backupbucket && exec /entrypoint.sh rustfs"]
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: RUSTFS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "rustfs.fullname" . }}
              key: AWS_ACCESS_KEY_ID
        - name: RUSTFS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "rustfs.fullname" . }}
              key: AWS_SECRET_ACCESS_KEY
        - name: RUSTFS_VOLUMES
          value: /data
        - name: RUSTFS_ADDRESS
          value: ":9000"
        - name: RUSTFS_CONSOLE_ENABLE
          value: "true"
        - name: RUSTFS_CONSOLE_ADDRESS
          value: ":9001"
        {{- if .Values.rustfs.tls.mount }}
        - name: RUSTFS_TLS_PATH
          value: /opt/tls
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
            scheme: {{ ternary "HTTPS" "HTTP" .Values.rustfs.tls.mount }}
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
            scheme: {{ ternary "HTTPS" "HTTP" .Values.rustfs.tls.mount }}
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: storage
          mountPath: "/data"
        {{- if .Values.rustfs.tls.mount }}
        - name: certificates
          mountPath: "/opt/tls"
          readOnly: true
        {{- end }}
      {{- if .Values.rustfs.tls.mount }}
      volumes:
      - name: certificates
        secret:
          secretName: {{ default (printf "%s-cert" (include "rustfs.fullname" .)) .Values.rustfs.tls.secret.name }}
          items:
          - key: tls.crt
            path: rustfs_cert.pem
          - key: tls.key
            path: rustfs_key.pem
      {{- end }}
      {{- if eq "true" ( include "distro.openshift" . ) }}
      securityContext:
        {{- toYaml (omit .Values.podSecurityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 8 }}
      {{- else }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
    {{- if or .Values.tolerations $criticalAddon }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $criticalAddon }}
        - key: CriticalAddonsOnly
          operator: Exists
      {{- end -}}
    {{- end -}}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $criticalAddon }}
      priorityClassName: system-cluster-critical
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- with .Values.storageClass.name }}
      storageClassName: {{ . }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
