{{- if and .Values.enabled .Values.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regcache.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "regcache.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.username | quote }}
  password: {{ .Values.password | quote }}
{{- end }}
