{{- if eq "prometheus.io/operator" ( include "monitoring.agent" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acerproxy.fullname" . }}-monitoring-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acerproxy.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "acerproxy.serviceAccountName" . }}
type: kubernetes.io/service-account-token
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "acerproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if eq "true" ( include "monitoring.apply-servicemonitor-label" . ) }}
    {{- include "monitoring.servicemonitor-label" . | nindent 4 }}
  {{- else }}
    {{- include "acerproxy.selectorLabels" . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "acerproxy.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: api
    authorization:
      type: Bearer
      credentials:
        name: {{ include "acerproxy.fullname" . }}-monitoring-token
        key: token
    scheme: https
    tlsConfig:
      ca:
        secret:
          name: {{ include "acerproxy.fullname" . }}-apiserver-cert
          key: ca.crt
      serverName: "{{ include "acerproxy.fullname" . }}.{{ .Release.Namespace }}.svc"
{{- end }}
